version: '3'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  todo-api:
    build:
      context: ./todo-api
    container_name: todo-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/todo_db
    command: ["sh", "-c", "go mod tidy && go run main.go"]
    
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile.dev
    container_name: react-app
    ports:
      - "3000:3000"
    depends_on:
      - todo-api

  nginx:
    depends_on:
      - todo-api
      - react-app
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

volumes:
  mongo_data:
